#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_SCRIPT="${ROOT_DIR}/scripts/check-ubuntu-relay-host.sh"

NODE_MAJOR="${NODE_MAJOR:-24}"
PNPM_VERSION="${PNPM_VERSION:-10.6.0}"
APP_USER="${APP_USER:-kodexlink}"
APP_GROUP="${APP_GROUP:-kodexlink}"
APP_DIR="${APP_DIR:-/srv/kodexlink}"
ETC_DIR="${ETC_DIR:-/etc/kodexlink}"
LOG_DIR="${LOG_DIR:-/var/log/kodexlink}"
RELAY_PORT="${RELAY_PORT:-8787}"
RELAY_DOMAIN="${RELAY_DOMAIN:-}"
SSL_CERT_PATH="${SSL_CERT_PATH:-}"
SSL_KEY_PATH="${SSL_KEY_PATH:-}"
DB_NAME="${DB_NAME:-codex_mobile}"
DB_USER="${DB_USER:-kodexlink}"
DB_PASSWORD="${DB_PASSWORD:-}"
SSH_UFW_PROFILE="${SSH_UFW_PROFILE:-OpenSSH}"
ENABLE_UFW_IF_INACTIVE="${ENABLE_UFW_IF_INACTIVE:-0}"
SYSTEMD_UNIT="/etc/systemd/system/kodexlink-relay.service"
NGINX_SITE="/etc/nginx/sites-available/kodexlink-relay.conf"
NGINX_SITE_ENABLED="/etc/nginx/sites-enabled/kodexlink-relay.conf"
RELAY_ENV_FILE="${ETC_DIR}/relay.env"
GENERATE_DB_PASSWORD=0
DRY_RUN=0
APP_HOME="/home/${APP_USER}"
NVM_DIR="${APP_HOME}/.nvm"

usage() {
  cat <<'EOF'
用法:
  sudo bash scripts/setup-ubuntu-relay-host.sh \
    --domain relay.example.com \
    --ssl-cert-path /path/fullchain.pem \
    --ssl-key-path /path/privkey.pem \
    [--db-password strong-password] \
    [--dry-run]

可选参数:
  --node-major 24
  --app-user kodexlink
  --app-group kodexlink
  --app-dir /srv/kodexlink
  --etc-dir /etc/kodexlink
  --log-dir /var/log/kodexlink
  --relay-port 8787
  --db-name codex_mobile
  --db-user kodexlink
  --db-password strong-password
  --ssh-ufw-profile OpenSSH
  --enable-ufw-if-inactive 0|1
  --dry-run
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      RELAY_DOMAIN="${2:-}"
      shift 2
      ;;
    --ssl-cert-path)
      SSL_CERT_PATH="${2:-}"
      shift 2
      ;;
    --ssl-key-path)
      SSL_KEY_PATH="${2:-}"
      shift 2
      ;;
    --node-major)
      NODE_MAJOR="${2:-}"
      shift 2
      ;;
    --app-user)
      APP_USER="${2:-}"
      shift 2
      ;;
    --app-group)
      APP_GROUP="${2:-}"
      shift 2
      ;;
    --app-dir)
      APP_DIR="${2:-}"
      shift 2
      ;;
    --etc-dir)
      ETC_DIR="${2:-}"
      RELAY_ENV_FILE="${ETC_DIR}/relay.env"
      shift 2
      ;;
    --log-dir)
      LOG_DIR="${2:-}"
      shift 2
      ;;
    --relay-port)
      RELAY_PORT="${2:-}"
      shift 2
      ;;
    --db-name)
      DB_NAME="${2:-}"
      shift 2
      ;;
    --db-user)
      DB_USER="${2:-}"
      shift 2
      ;;
    --db-password)
      DB_PASSWORD="${2:-}"
      shift 2
      ;;
    --ssh-ufw-profile)
      SSH_UFW_PROFILE="${2:-}"
      shift 2
      ;;
    --enable-ufw-if-inactive)
      ENABLE_UFW_IF_INACTIVE="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[setup] 未知参数: $1" >&2
      usage
      exit 1
      ;;
  esac
done

log() {
  printf '[setup] %s\n' "$1"
}

dry_log() {
  printf '[setup][dry-run] %s\n' "$1"
}

fail() {
  printf '[setup][ERROR] %s\n' "$1" >&2
  exit 1
}

require_root() {
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "dry-run 模式跳过 root 权限要求"
    return
  fi
  if [[ "${EUID}" -ne 0 ]]; then
    fail "请使用 root 或 sudo 运行"
  fi
}

validate_name() {
  local value="$1"
  local label="$2"
  if [[ ! "${value}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
    fail "${label} 格式非法: ${value}"
  fi
}

escape_sql_literal() {
  printf "%s" "$1" | sed "s/'/''/g"
}

ensure_required_inputs() {
  [[ -n "${RELAY_DOMAIN}" ]] || fail "缺少 --domain / RELAY_DOMAIN"
  [[ -n "${SSL_CERT_PATH}" ]] || fail "缺少 --ssl-cert-path / SSL_CERT_PATH"
  [[ -n "${SSL_KEY_PATH}" ]] || fail "缺少 --ssl-key-path / SSL_KEY_PATH"
  validate_name "${DB_NAME}" "DB_NAME"
  validate_name "${DB_USER}" "DB_USER"

  if [[ -z "${DB_PASSWORD}" ]]; then
    if [[ "${DRY_RUN}" == "1" ]]; then
      DB_PASSWORD="<auto-generated-on-real-run>"
    else
      GENERATE_DB_PASSWORD=1
    fi
  fi
}

run_preflight_check() {
  log "执行安装前环境检查"
  bash "${CHECK_SCRIPT}" \
    --phase preflight \
    --domain "${RELAY_DOMAIN}" \
    --ssl-cert-path "${SSL_CERT_PATH}" \
    --ssl-key-path "${SSL_KEY_PATH}" \
    --app-user "${APP_USER}" \
    --app-dir "${APP_DIR}" \
    --etc-dir "${ETC_DIR}" \
    --relay-port "${RELAY_PORT}" \
    --db-name "${DB_NAME}" \
    --db-user "${DB_USER}" \
    --node-major "${NODE_MAJOR}"
}

install_base_packages() {
  log "安装基础依赖"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将执行: apt-get update"
    dry_log "将执行: apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common git build-essential ufw"
    return
  fi

  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    apt-transport-https \
    software-properties-common \
    git \
    build-essential \
    ufw

  if [[ "${GENERATE_DB_PASSWORD}" == "1" ]]; then
    DB_PASSWORD="$(openssl rand -hex 24)"
    log "未提供 DB_PASSWORD，已自动生成随机密码"
  fi
}

install_nodejs() {
  log "通过 nvm 安装 Node.js ${NODE_MAJOR}"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将以用户 ${APP_USER} 安装 nvm 到 ${NVM_DIR}"
    dry_log "将执行: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash"
    dry_log "将执行: source ${NVM_DIR}/nvm.sh"
    dry_log "将执行: nvm install ${NODE_MAJOR}"
    dry_log "将执行: corepack enable"
    dry_log "将执行: corepack prepare pnpm@${PNPM_VERSION} --activate"
    return
  fi

  runuser -u "${APP_USER}" -- /bin/bash -lc "export NVM_DIR='${NVM_DIR}'; mkdir -p \"\$NVM_DIR\"; curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash"
  runuser -u "${APP_USER}" -- /bin/bash -lc "export NVM_DIR='${NVM_DIR}'; . \"\$NVM_DIR/nvm.sh\" && nvm install ${NODE_MAJOR} && nvm alias default ${NODE_MAJOR} && corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate"
}

install_server_packages() {
  log "安装 Nginx / PostgreSQL / Redis"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将执行: apt-get install -y nginx postgresql postgresql-contrib redis-server redis-tools"
    dry_log "将执行: systemctl enable nginx postgresql redis-server"
    dry_log "将执行: systemctl restart nginx postgresql redis-server"
    return
  fi

  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nginx \
    postgresql \
    postgresql-contrib \
    redis-server \
    redis-tools

  systemctl enable nginx
  systemctl enable postgresql
  systemctl enable redis-server
  systemctl restart nginx
  systemctl restart postgresql
  systemctl restart redis-server
}

create_system_user_and_dirs() {
  log "创建系统用户与目录"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将确保系统组存在: ${APP_GROUP}"
    dry_log "将确保系统用户存在: ${APP_USER}"
    dry_log "将创建目录: ${APP_DIR}"
    dry_log "将创建目录: ${ETC_DIR}"
    dry_log "将创建目录: ${LOG_DIR}"
    return
  fi

  if ! getent group "${APP_GROUP}" >/dev/null 2>&1; then
    groupadd --system "${APP_GROUP}"
  fi

  if ! id "${APP_USER}" >/dev/null 2>&1; then
    useradd --system --gid "${APP_GROUP}" --create-home --shell /bin/bash "${APP_USER}"
  fi

  install -d -m 0755 -o "${APP_USER}" -g "${APP_GROUP}" "${APP_DIR}"
  install -d -m 0755 -o root -g "${APP_GROUP}" "${ETC_DIR}"
  install -d -m 0755 -o "${APP_USER}" -g "${APP_GROUP}" "${LOG_DIR}"
}

configure_postgresql() {
  log "配置 PostgreSQL 数据库与账号"
  local escaped_password
  escaped_password="$(escape_sql_literal "${DB_PASSWORD}")"

  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将执行: 创建或更新 PostgreSQL 角色 ${DB_USER}"
    dry_log "将执行: 创建数据库 ${DB_NAME}，owner=${DB_USER}"
    return
  fi

  runuser -u postgres -- psql postgres <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${escaped_password}';
  ELSE
    ALTER ROLE ${DB_USER} WITH LOGIN PASSWORD '${escaped_password}';
  END IF;
END
\$\$;
SQL

  if ! runuser -u postgres -- psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}'" | grep -q '^1$'; then
    runuser -u postgres -- createdb --owner="${DB_USER}" "${DB_NAME}"
  fi
}

write_relay_env() {
  log "写入 Relay 生产环境变量文件"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将写入文件: ${RELAY_ENV_FILE}"
    cat <<EOF
[setup][dry-run] ===== ${RELAY_ENV_FILE} =====
NODE_ENV=production
PORT=${RELAY_PORT}
RELAY_BIND_HOST=127.0.0.1
RELAY_PUBLIC_BASE_URL=https://${RELAY_DOMAIN}
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
REDIS_URL=redis://127.0.0.1:6379
RELAY_ENABLE_DEV_RESET=0
[setup][dry-run] ============================
EOF
    return
  fi

  cat > "${RELAY_ENV_FILE}" <<EOF
NODE_ENV=production
PORT=${RELAY_PORT}
RELAY_BIND_HOST=127.0.0.1
RELAY_PUBLIC_BASE_URL=https://${RELAY_DOMAIN}
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
REDIS_URL=redis://127.0.0.1:6379
RELAY_ENABLE_DEV_RESET=0
EOF
  chown root:"${APP_GROUP}" "${RELAY_ENV_FILE}"
  chmod 0640 "${RELAY_ENV_FILE}"
}

write_systemd_unit() {
  log "写入 systemd unit"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将写入文件: ${SYSTEMD_UNIT}"
    cat <<EOF
[setup][dry-run] ===== ${SYSTEMD_UNIT} =====
[Unit]
Description=KodexLink Relay Server
After=network-online.target postgresql.service redis-server.service
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${RELAY_ENV_FILE}
Environment=NVM_DIR=${NVM_DIR}
ExecStartPre=/usr/bin/test -f ${APP_DIR}/runtime-apps/relay-server/dist/server.js
ExecStartPre=/bin/bash -lc 'export NVM_DIR=${NVM_DIR}; . "${NVM_DIR}/nvm.sh"; cd ${APP_DIR} && pnpm --filter @kodexlink/relay-server migrate'
ExecStart=/bin/bash -lc 'export NVM_DIR=${NVM_DIR}; . "${NVM_DIR}/nvm.sh"; cd ${APP_DIR} && exec node runtime-apps/relay-server/dist/server.js serve'
Restart=always
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
[setup][dry-run] ============================
EOF
    dry_log "将执行: systemctl daemon-reload"
    return
  fi

  cat > "${SYSTEMD_UNIT}" <<EOF
[Unit]
Description=KodexLink Relay Server
After=network-online.target postgresql.service redis-server.service
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${RELAY_ENV_FILE}
Environment=NVM_DIR=${NVM_DIR}
ExecStartPre=/usr/bin/test -f ${APP_DIR}/runtime-apps/relay-server/dist/server.js
ExecStartPre=/bin/bash -lc 'export NVM_DIR=${NVM_DIR}; . "${NVM_DIR}/nvm.sh"; cd ${APP_DIR} && pnpm --filter @kodexlink/relay-server migrate'
ExecStart=/bin/bash -lc 'export NVM_DIR=${NVM_DIR}; . "${NVM_DIR}/nvm.sh"; cd ${APP_DIR} && exec node runtime-apps/relay-server/dist/server.js serve'
Restart=always
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
  chmod 0644 "${SYSTEMD_UNIT}"
  systemctl daemon-reload
}

write_nginx_site() {
  log "写入 Nginx 站点配置"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将写入文件: ${NGINX_SITE}"
    cat <<EOF
[setup][dry-run] ===== ${NGINX_SITE} =====
server {
    listen 80;
    listen [::]:80;
    server_name ${RELAY_DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${RELAY_DOMAIN};

    ssl_certificate ${SSL_CERT_PATH};
    ssl_certificate_key ${SSL_KEY_PATH};
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /v1/connect {
        proxy_pass http://127.0.0.1:${RELAY_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass http://127.0.0.1:${RELAY_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }
}
[setup][dry-run] ============================
EOF
    dry_log "将执行: ln -sfn ${NGINX_SITE} ${NGINX_SITE_ENABLED}"
    dry_log "将执行: nginx -t"
    dry_log "将执行: systemctl reload nginx"
    return
  fi

  cat > "${NGINX_SITE}" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${RELAY_DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${RELAY_DOMAIN};

    ssl_certificate ${SSL_CERT_PATH};
    ssl_certificate_key ${SSL_KEY_PATH};
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /v1/connect {
        proxy_pass http://127.0.0.1:${RELAY_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }

    location / {
        proxy_pass http://127.0.0.1:${RELAY_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }
}
EOF

  ln -sfn "${NGINX_SITE}" "${NGINX_SITE_ENABLED}"
  nginx -t
  systemctl reload nginx
}

configure_ufw() {
  if ! command -v ufw >/dev/null 2>&1; then
    log "UFW 未安装，跳过防火墙配置"
    return
  fi

  log "配置 UFW 规则"
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "将执行: ufw allow ${SSH_UFW_PROFILE}"
    dry_log "将执行: ufw allow Nginx Full"
    if [[ "${ENABLE_UFW_IF_INACTIVE}" == "1" ]]; then
      dry_log "若 UFW 未激活，将执行: ufw enable"
    else
      dry_log "若 UFW 未激活，将不会自动启用"
    fi
    return
  fi

  ufw allow "${SSH_UFW_PROFILE}" >/dev/null
  ufw allow 'Nginx Full' >/dev/null

  local status
  status="$(ufw status 2>/dev/null | head -n 1 || true)"
  if [[ "${status}" == "Status: active" ]]; then
    ufw reload >/dev/null
    log "UFW 已激活，已刷新规则"
    return
  fi

  if [[ "${ENABLE_UFW_IF_INACTIVE}" == "1" ]]; then
    yes | ufw enable >/dev/null
    log "UFW 原本未激活，已按要求启用"
  else
    log "UFW 当前未激活，未自动启用；如需启用请手动执行: ufw enable"
  fi
}

run_postinstall_check() {
  if [[ "${DRY_RUN}" == "1" ]]; then
    dry_log "dry-run 模式跳过安装后环境检查"
    return
  fi

  log "执行安装后环境检查"
  bash "${CHECK_SCRIPT}" \
    --phase postinstall \
    --domain "${RELAY_DOMAIN}" \
    --ssl-cert-path "${SSL_CERT_PATH}" \
    --ssl-key-path "${SSL_KEY_PATH}" \
    --app-user "${APP_USER}" \
    --app-dir "${APP_DIR}" \
    --etc-dir "${ETC_DIR}" \
    --relay-port "${RELAY_PORT}" \
    --db-name "${DB_NAME}" \
    --db-user "${DB_USER}" \
    --node-major "${NODE_MAJOR}" \
    --systemd-unit "${SYSTEMD_UNIT}" \
    --nginx-site "${NGINX_SITE}"
}

print_next_steps() {
  if [[ "${DRY_RUN}" == "1" ]]; then
    cat <<EOF

[setup][dry-run] 模拟运行完成，未对系统做任何修改。

将要写入:
  env 文件: ${RELAY_ENV_FILE}
  systemd: ${SYSTEMD_UNIT}
  nginx 配置: ${NGINX_SITE}

将要准备:
  应用目录: ${APP_DIR}
  日志目录: ${LOG_DIR}
  数据库: ${DB_NAME}
  数据库用户: ${DB_USER}
  数据库密码: ${DB_PASSWORD}

真实执行时使用:
  sudo bash scripts/setup-ubuntu-relay-host.sh \\
    --domain ${RELAY_DOMAIN} \\
    --ssl-cert-path ${SSL_CERT_PATH} \\
    --ssl-key-path ${SSL_KEY_PATH} \\
    --db-password '${DB_PASSWORD}'

EOF
    return
  fi

  cat <<EOF

[setup] 环境搭建完成。

关键信息:
  应用目录: ${APP_DIR}
  env 文件: ${RELAY_ENV_FILE}
  systemd: ${SYSTEMD_UNIT}
  nginx 配置: ${NGINX_SITE}
  Relay 域名: https://${RELAY_DOMAIN}
  数据库: ${DB_NAME}
  数据库用户: ${DB_USER}
  数据库密码: ${DB_PASSWORD}

后续手工步骤:
  1. 把仓库代码部署到 ${APP_DIR}
  2. 在 ${APP_DIR} 执行:
       pnpm install --frozen-lockfile
       pnpm build
  3. 首次上线迁移:
       pnpm relay-server:migrate
  4. 启用并启动 Relay:
       systemctl enable kodexlink-relay
       systemctl restart kodexlink-relay
  5. 检查:
       systemctl status kodexlink-relay
       curl -I https://${RELAY_DOMAIN}/healthz

EOF
}

require_root
ensure_required_inputs
run_preflight_check
install_base_packages
install_nodejs
install_server_packages
create_system_user_and_dirs
configure_postgresql
write_relay_env
write_systemd_unit
write_nginx_site
configure_ufw
run_postinstall_check
print_next_steps
